config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about"=> "pages#about"
  resources "articles"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum:3, maximum:500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
        @article = Article.new
    end

    def index
        @article = Article.all
    end

    def edit
        @article = Article.find(params[:id])
    end

    def show
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Artcle was successfully created."
            redirect_to article_path(@article)
        else
            render "new"
        end
    end

    private
    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home

    end
    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<!-- FORM POST -->
<%= form_for @article do |t| %>
    <p>
        <%= t.label :title %>
        <%= t.text_field :title %>
    </p>
    <p>
        <%= t.label :description %>
        <%= t.text_area :description %>
    </p>
    <p>
        <%= t.submit %>
    </p>
<% end %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<table>
    <tr>
        <td>Title</td>
        <td>Description</td>
    </tr>
    <% @article.each do |item| %>
    <tr>
        <td>
            <%= item.title %>
        </td>
        <td>
            <%= item.description %>
        </td>
        <td>
            <%= link_to "Edit", edit_article_path(item.id) %>
        </td>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<!-- FORM POST -->
<%= form_for @article do |t| %>
    <p>
        <%= t.label :title %>
        <%= t.text_field :title %>
    </p>
    <p>
        <%= t.label :description %>
        <%= t.text_area :description %>
    </p>
    <p>
        <%= t.submit %>
    </p>
<% end %>

<!--
FORM GET
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
 -->

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>
    Title: <%= @article.title %>
</p>

<p>
    Description: <%= @article.description %>
</p>
<%= link_to("Back to Article", articles_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>

    <ul>

    <li><%= msg %></li>

    </ul>

    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about Page</h1>

<%= link_to("Home",root_path) %>

app/views/pages/home.html.erb
<h1>This is home Page</h1>


<%= link_to("About", about_path) %>